#############################

# REFERENCE TUNE AZ PYTHIA8 (MCNNTUNE)
# Runcard for performing the tune using the
# phi_eta^star measurements
# following arXiv:1406.3660.

#############################
input:
  folders:
    - ../../mcnntunes_data/theory_input_3params_mpipt0_2.18/runs
  patterns:
    - '/ATLAS_2012_I1204784/d02-x01-y01'
    - '/ATLAS_2012_I1204784/d02-x01-y02'    
  unpatterns:
    - 'None'
  expfiles:
    - '../../mcnntunes_data/theory_input_3params_mpipt0_2.18/expdata/ATLAS_2012_I1204784.yoda'
  weightrules:
    - pattern: '/ATLAS_2012_I1204784/d02-x01-y01'
      condition: [0.28,'+inf']
      weight: 0
    - pattern: '/ATLAS_2012_I1204784/d02-x01-y02'
      condition: [0.28,'+inf'] 
      weight: 0

#############################
model:
  type: 'DirectModel'
  seed: 0

  noscan_setup:
    optimizer: 'adam'
    epochs: 15000
    batch_size: 20
    architecture: [3,5]
    actfunction: 'tanh'

##############################
minimizer:
  type: 'CMAES'
  bounds: on
  restarts: 2
