#############################

# REFERENCE TUNE AZ PYTHIA8 (MCNNTUNE)
# Runcard for performing the tune using the
# ptZ measurements
# following arXiv:1406.3660.

#############################
input:
  folders:
    - ../../mcnntunes_data/theory_input_3params_mpipt0_2.18/runs
  patterns:
    - '/ATLAS_2014_I1300647/d01-x01-y01'
    - '/ATLAS_2014_I1300647/d01-x01-y02'    
  unpatterns:
    - 'None'
  expfiles:
    - '../../mcnntunes_data/theory_input_3params_mpipt0_2.18/expdata/ATLAS_2014_I1300647.yoda'
  weightrules:
    - pattern: '/ATLAS_2014_I1300647/d01-x01-y01'
      condition: [26,'+inf']
      weight: 0
    - pattern: '/ATLAS_2014_I1300647/d01-x01-y02'
      condition: [26,'+inf']
      weight: 0

#############################
model:
  seed: 0
  scan: off

  scan_setup:
    nb_epoch: [10000, 15000]
    batch_size: [20, 50, 100, 200]
    optimizer: ['rmsprop', 'adam', 'sgd']
    architecture: [[6,15],[3,5],[6,15,8]]
    actfunction: ['tanh','sigmoid','relu']
    kfold: 3

  noscan_setup:
    optimizer: 'adam'
    nb_epoch: 15000
    batch_size: 20
    architecture: [3,5]
    actfunction: 'tanh'

##############################
minimizer:
  bounds: on
  restarts: 2
