# Example of runcard for MCNNTUNE

#############################
input:
  folders:
    - theory_input
  patterns:
    - '.*/ATLAS_2016_I1424838/d.*-x01.*'
  unpatterns:
    - 'None'
  expfiles:
    - 'data/ATLAS_2016_I1424838.yoda'

#############################
model:
  type: 'DirectModel'
  seed: 0

  noscan_setup:
    optimizer: 'rmsprop'
    epochs: 10000
    batch_size: 20
    architecture: [6,15]
    actfunction: 'tanh'

##############################
minimizer:
  type: 'CMAES'
  bounds: on
  restarts: 0
