# Example of runcard for MCNNTUNE

#############################
input:
  folders:
    - theory_input_7params_0118
  patterns:
#    - '.*/ATLAS_2012_I1204784/d01-x01-y01'
#    - '.*/ATLAS_2016_I1424838/d03-x01-y01'
#    - '.*/ATLAS_2016_I1424838/d03-x01-y02'
    - '.*/ATLAS_2013_I1230812/d01-x01-y01'
    
  unpatterns:
    - 'None'
  expfiles:
    - '/usr/local/share/Rivet/ATLAS_2013_I1230812.yoda'
  #weight_bins: off TODO

#############################
model:
  seed: 0
  scan: off

  scan_setup:
    nb_epoch: [10000, 15000]
    batch_size: [20, 50, 100, 200]
    optimizer: ['rmsprop', 'adam', 'sgd']
    architecture: [[6,15],[3,5],[6,15,8]]
    actfunction: ['tanh','sigmoid','relu']
    kfold: 3

  noscan_setup:
    optimizer: 'adam'
    nb_epoch: 15000
    batch_size: 20
    architecture: [6,15]
    actfunction: 'tanh'

##############################
minimizer:
  bounds: on
  restarts: 2
