# Example of runcard for MCNNTUNE

#############################
input:
  seed: 0
  folders:
    - theory_input
  patterns:
    - '/ATLAS_2016_I1424838/d03-x01-y01'
  unpatterns:
    - 'None'
  expfiles:
    - 'data/ATLAS_2016_I1424838.yoda'
  #weight_bins: off TODO

#############################
model:
  scan: on

  scan_setup:
    nb_epoch: [10, 20]
    batch_size: [50, 100, 200]
    optimizer: ['rmsprop']
    architecture: [[6,15]]
    actfunction: ['tanh','sigmoid','relu']
    kfold: 3

  noscan_setup:
    optimizer: 'rmsprop'
    nb_epoch: 10000
    batch_size: 200
    architecture: [6,15]
    actfunction: 'tanh'

##############################
minimizer:
  bounds: on