# Example of runcard for MCNNTUNE

#############################
input:
  folders:
    - theory_input_7params_0118
  patterns:
#    - '.*/ATLAS_2012_I1204784/d01-x01-y01'
#    - '.*/ATLAS_2016_I1424838/d03-x01-y01'
#    - '.*/ATLAS_2016_I1424838/d03-x01-y02'
    - '.*/ATLAS_2013_I1230812/d01-x01-y01'
    
  unpatterns:
    - 'None'
  expfiles:
    - '/usr/local/share/Rivet/ATLAS_2013_I1230812.yoda'

#############################
model:
  type: 'DirectModel'
  seed: 0

  noscan_setup:
    optimizer: 'adam'
    epochs: 15000
    batch_size: 20
    architecture: [6,15]
    actfunction: 'tanh'

##############################
minimizer:
  type: 'CMAES'
  bounds: on
  restarts: 2
