# Example of runcard for MCNNTUNE

#############################
input:
  folders:
    - theory_input
  patterns:
    - '.*/ATLAS_2016_I1424838/d.*-x01.*'
  unpatterns:
    - 'None'
  expfiles:
    - 'data/ATLAS_2016_I1424838.yoda'
  weight_bins: off

#############################
model:
  seed: 0
  scan: off

  scan_setup:
    nb_epoch: [1000, 2000, 5000]
    batch_size: [20, 50, 100, 200]
    optimizer: ['rmsprop', 'adam', 'sgd']
    architecture: [[6,15],[3,5],[3,3,3]]
    actfunction: ['tanh','sigmoid','relu']
    kfold: 3

  noscan_setup:
    optimizer: 'rmsprop'
    nb_epoch: 10000
    batch_size: 20
    architecture: [6,15]
    actfunction: 'tanh'

##############################
minimizer:
  bounds: on
  restarts: 0
