# Example of runcard for MCNNTUNE

#############################
input:
  folders:
    - theory_input
  patterns:
    - '/ATLAS_2016_I1424838/d03-x01-y01'
  unpatterns:
    - 'None'
  expfiles:
    - 'data/ATLAS_2016_I1424838.yoda'
  #weight_bins: off TODO

#############################
model:
  scan: off

  scan_setup:
    nb_epoch: [1000, 2000, 5000]
    batch_size: [50, 100, 200]
    loss: ['mse']
    architecture: [[6,15]]
    actfunction: ['tanh','sigmoid','relu']

  noscan_setup:
    optimizer: 'rmsprop'
    loss: 'mse'
    nb_epoch: 10000
    batch_size: 200
    architecture: [6,15]
    actfunction: 'tanh'

##############################
minimizer:
  bounds: on